name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install AWS CLI and jq
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq awscli jq

    - name: Download and upload files to S3
      run: |
        # Read download_links.json
        LINKS=$(cat download_links.json)
        
        # Iterate over each entry in the JSON array
        for row in $(echo "${LINKS}" | jq -r '.[] | @base64'); do
          _jq() {
            echo ${row} | base64 --decode | jq -r ${1}
          }
          
          URL=$(_jq '.url')
          TIMES=$(_jq '.times')
          
          FILE_NAME=$(basename ${URL})
          DOWNLOAD_FILE="downloaded_${FILE_NAME}"
          
          # Download the file once (suppress output, show errors)
          wget ${URL} -O ${DOWNLOAD_FILE} > /dev/null
          
          for ((i=1;i<=TIMES;i++)); do
            UPLOAD_FILE="Test_${FILE_NAME%.txt}_$i.txt"
            
            # Upload to S3 with a different name (suppress output, show errors)
            aws s3 cp ${DOWNLOAD_FILE} s3://iconik-s3-test/${UPLOAD_FILE}
          done
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
